### ISSUE TITLE
Not Artificial Intelligence / Machine Learning

### ISSUE THREAD

**Issue by robbiebarrat** [zackthoutt/sudoku-ai#1]
This is just a normal algorithm; no machine learning or AI is involved so it shouldn't be called sudoku-ai.

maybe 'sudoku-bot'?

**Comment by zackthoutt** [comment]
In the README I explain that there is no machine learning involved and that's actually a reason I think this AI is cool. This is still AI though. Not all AI is machine learning. Machine learning is the most common and "advanced" approach to AI, but it is not the only one. 

https://www.quora.com/What-are-the-main-differences-between-artificial-intelligence-and-machine-learning-Is-machine-learning-a-part-of-artificial-intelligence

**Comment by zackthoutt** [comment]
There are tons of examples of AI that don't use machine learning, and they're often actually the most successful AIs. Google Maps routing, a lot of game playing agents, self-driving cars, etc. use AI that is not machine learning.

**Comment by robbiebarrat** [comment]
By that definition pretty much every algorithm could be classified as "AI", even things like sorting algorithms...

I wouldn't call Google Maps 'AI' - and while self-driving cars do have some rule-based algorithms in them (I work with self driving cars) - I'm not aware of anyone making any without a heavy ML part.

But if you're using the definition that to be considered as "artificial intelligence" an ability to learn isn't required; then yeah your sudoku program is "AI"

**Comment by zackthoutt** [comment]
I totally get what you mean. I think it's a bit of a philosophical question. The requirement where I draw the line is that AI can be algorithms--there doesn't need to be machine learning--but it has to include significant domain knowledge specific to the problem. So a sorting algorithm wouldn't be AI, but a Sudoku solver would be.

I would also definitely call Google Maps an AI. Think about how long it would take you to find the optimal route without Google Maps. There is a famous AI researcher, I forget his name, but he says that a common paradox of AI is that we consider something to be AI while it is being researched, but once the problem is solved and we understand it, people gradually stop considering it to be AI. By definition though, I think these algorithms are AI, even though they don't use machine learning.

**Comment by zackthoutt** [comment]
@robbiebarrat, you have some cool projects by the way. I'm also interested in the intersection of art and AI. Have you read about CANs or ever tried to get one working?
